config/routes.rb
Rails.application.routes.draw do

  resources :midpoints do
    resource :json_data
    resource :venues
    resource :notifications
  end

  root to: 'midpoints#new'

end

app/models/midpoint.rb
require_relative 'calculators/midpoint_calculator'

class Midpoint < ActiveRecord::Base
  
  LATITUDE_RANGE = (-90..90)
	LONGITUDE_RANGE = (-180..180)

  has_many :addresses

	validates :lat, presence: { message: 'You must include a latitude' }
	validates :lng, presence: { message: 'You must include a longitude' }

	validates :lat, numericality: { message: 'Latitude must be a number' }
	validates :lng, numericality: { message: 'Longitude must be a number' }

	validates :lat, inclusion: { in: LATITUDE_RANGE , message: 'Latitude must be between -90 and 90' }
	validates :lng, inclusion: { in: LONGITUDE_RANGE , message: 'Longitude must be between -180 and 180' }


	def self.create_from(address_list)
		Midpoint.create.add_addresses_from(address_list).create_location

	end

	def add_addresses_from(address_list)
    address_list.map { |address| addresses << Address.create(full_address: address["full_address"], lat: address["lat"], lng: address["lng"]) }
    self
	end

# This is where you can change which midpoint calculator to use
	def create_location
		start_coordinates = addresses.map{ |address| Coordinate.create_from(address) }
    midpoint_coordinates = MidpointCalculator.midpoint_by(:drive_time, start_coordinates)
    self.update(lat: midpoint_coordinates.lat, lng: midpoint_coordinates.lng)
		self
	end

end

app/controllers/midpoints_controller.rb
require 'calculators/midpoint_calculator'

class MidpointsController < ApplicationController

  def create
    params[:addresses].delete_if { |item| item["address"] == "" }
    redirect_to midpoint_path(Midpoint.create_from(params[:addresses]))
  end

  def show
    @midpoint = Midpoint.find(params[:id])
  end

end

app/views/midpoints/_new_sidebar.html.erb
<%= form_tag(midpoints_path, class: "new_midpoint") do %>

  <section class="address-form">

    <%= text_field_tag("addresses[][address]", nil, class: "address form-control", placeholder: "Address 1") %>
    <%= hidden_field_tag 'addresses[][full_address]', nil, id: 'full_address_1' %>
    <%= hidden_field_tag 'addresses[][lat]', nil, id: 'lat_1' %>
    <%= hidden_field_tag 'addresses[][lng]', nil, id: 'lng_1' %><br />
    
    <%= text_field_tag("addresses[][address]", nil, class: "address form-control", placeholder: "Address 2") %>
    <%= hidden_field_tag 'addresses[][full_address]', nil, id: 'full_address_2' %>
    <%= hidden_field_tag 'addresses[][lat]', nil, id: 'lat_2' %>
    <%= hidden_field_tag 'addresses[][lng]', nil, id: 'lng_2' %><br />
  
  </section>
  
  <footer>
    <a id='new-address-form' href='#'>+ Add another address...</a>
    
    <p><%= submit_tag "Bunch us!", class: 'btn btn-info bunch-submit' %></p>
  </footer>
  
<% end %>

<section class='js_errors'>
  <%= render partial: 'layouts/js_flash' %>
</section>



<script id='address_form_template' type='x-tmpl-mustache'>
	
	<input class="address form-control" id="address_{{ index }}" name="addresses[][address]" type="text" placeholder="Address {{ index }}">
	<input id="full_address_{{ index }}" name="addresses[][full_address]" type="hidden">
	<input id="lat_{{ index }}" name="addresses[][lat]" type="hidden">
	<input id="lng_{{ index }}" name="addresses[][lng]" type="hidden"><br />

</script>

app/views/midpoints/_sidebar.html.erb
<p id='tagline'>Where is everyone?</p>

<%= form_tag(midpoints_path, class: "new_midpoint") do %>

  <section class="address-form">
  </section>
  
  <footer>
    <p><%= submit_tag "Bunch us!", class: 'btn btn-lg btn-info bunch-submit' %></p>
  </footer>
  
<% end %>

<section id='js-flash'></section>


<script id='address_form_template' type='x-tmpl-mustache'>
  
  <input class="address form-control" id="address_{{ index }}" name="addresses[][address]" type="text" placeholder="Address {{ index }}">
  <input id="full_address_{{ index }}" name="addresses[][full_address]" type="hidden">
  <input id="lat_{{ index }}" name="addresses[][lat]" type="hidden">
  <input id="lng_{{ index }}" name="addresses[][lng]" type="hidden"><br />

</script>

app/views/midpoints/new.html.erb
<div id="bunch-carousel" class="carousel fade" data-ride="carousel">
	<div class="carousel-inner">
		<div class="active item one"></div>
		<div class="item two"></div>
		<div class="item three"></div>
		<div class="item four"></div>
		<div class="item five"></div>
		<div class="item six"></div>
	</div>
</div>

<section class="foreground">
	<div class="sidebar-wrapper">
			<aside class='sidebar'>

				<div id="content-container">
				  <header class='sidebar-header'>
				    <section class='logo-and-text'>
				      <a href="/" class="logo"><%= image_tag 'grapes_white.png', id: 'grapes_logo' %>bunch</a>
				    </section>
				  </header>

				  <article class='sidebar-body'>
				    <%= render partial: 'midpoints/sidebar' %>     
				  </article>

				  <footer class='sidebar-footer'>
				    <%= render partial: 'layouts/footer' %>
				  </footer>
			  </div>
			  
			</aside>
	</div>


	<div>
		<section class='main-area'>
				<%= image_tag 'bunch-welcome.png', id: 'bunch-welcome' %>
		</section>
	</div>
</section>

app/views/midpoints/show.html.erb
<section class="background">

	<section id="main_map_holder">
		<figure id="main_map" class="map-css">

		</figure>
	</section>

	<section class="sidebar-wrapper">
		<aside class='sidebar'>
			<div id="content-container">

			  <header class='sidebar-header'>
			    <section class='logo-and-text'>
			      <a href="/" class="logo"><%= image_tag 'grapes_white.png', id:'grapes_logo' %>bunch</a>
			    </section>
			  </header>

			  <article class='sidebar-body'>
			    <%= render partial: 'venues/sidebar' %>     
			  </article>

			  <section id='map_data'>
					<var id='midpoint_id' ><%= @midpoint.id %></var>
				</section>

			  <footer class='sidebar-footer'>
			    <%= render partial: 'layouts/footer' %>
			 	 </footer>
			  
		  </div>
		</aside>
	</section>

	<section id="zoom-button-area">
		<button id="map-zoom-in" class="btn-lg zoom-button ">Venues view</button>
		<button id="map-zoom-out" class="btn-lg zoom-button active-zoom-button">Route view</button>
	</section>
	
	<!-- Modal placeholder 	-->
	<%= render partial: 'notifications/modal' %>

</section>