config/routes.rb
Rails.application.routes.draw do

  resources :midpoints do
    resource :json_data
    resource :venues
    resource :notifications
  end

  root to: 'midpoints#new'

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

	def create
		send_notification(params, generate_meetup_details(params))
		redirect_to new_midpoint_path
	end

	def generate_meetup_details(params)
		"'#{params[:message]}'\n- #{params[:user_name]} bunched you!\nMeet @ #{params[:meetup_venue]} @ #{params[:meetup_time]}\nVenue details: #{params[:meetup_url]}\nPowered by ©bunch" 
	end

	def send_notification(params, meetup_details)
		SMSNotifier.send_meetup_sms(params[:phone_numbers].split(','), meetup_details)
	end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<article class='container'>
  <%= form_tag(midpoint_notifications_path(@midpoint), class: "new_notification") do %>

    <section class="notification-form">

      <%= text_field_tag("user_name", nil, required: true, class: "form-control", placeholder: "Your name") %>

      <%= text_field_tag("phone_numbers", nil, required: true, class: "form-control", placeholder: "Phone numbers") %>

      <%= text_field_tag("message", nil, required: true, class: "form-control", placeholder: "Your message") %>

      <%= hidden_field_tag 'meetup_url', nil, id: 'meetup_url', value: '' %>
      <%= hidden_field_tag 'meetup_venue', nil, id: 'meetup_venue', value: '' %>

      <div class="form-group">
        <div class='input-group date' id='datetimepicker1'>
            <input type='text' class="form-control" name='meetup_time' placeholder='DD/MM/YYYY HH:MM' />
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
      </div>
    
    </section>
    
    <footer>    
      <p><%= submit_tag "Send", class: 'btn btn-info notification-submit' %></p>
    </footer>
    
  <% end %>
</article>

app/views/notifications/_modal.html.erb
<div class="modal fade" id="newNotificationModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">
        	<i class="fa fa-send"></i>
        	<span>Send Meetup Notifications</span>
        </h4>
      </div>
      <div class="modal-body">
      	<%= render 'notifications/form' %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/new.html.erb
<%= render partial: 'form' %>