config/routes.rb
Rails.application.routes.draw do

  resources :midpoints do
    resource :json_data
    resource :venues
    resource :notifications
  end

  root to: 'midpoints#new'

end

app/models/venues/venue.rb
class Venue

  DEFAULT = 'N/A'
    
  attr_reader :name, :full_address, :lat, :lng, :category, :price_tier, :rating, :id, :icon

  def initialize venue_information 
    @name = venue_information["name"]
    @full_address = venue_information["location"]["formattedAddress"]
    @lat = venue_information["location"]["lat"]
    @lng = venue_information["location"]["lng"] 
    @category = venue_information.fetch("categories", [{}])[0].fetch("name", DEFAULT) 
    @price_tier = venue_information.fetch("price", {}).fetch("tier", DEFAULT)
    @rating = venue_information.fetch("rating", 0)
    @id = venue_information["id"]
    @icon = venue_information.fetch("categories", [{}])[0].fetch("icon", DEFAULT).values
  end
end

app/models/venues/venue_data_retriever.rb
class VenueDataRetriever

  NUMBER_OF_VENUES = 50
  NUMBER_TO_SELECT = 3
  DEFAULT_RADIUS = 250
  RADIUS_INCREMENT = 250
  MIN_NUMBER_OF_VENUES = 20

  FOURSQUARE_ID = Rails.application.secrets.foursquare_client_id
  FOURSQUARE_SECRET = Rails.application.secrets.foursquare_client_secret

  BASE_URI = 'https://api.foursquare.com/v2/venues/explore?'

  def self.create_venues(data)
    (0...venue_count(data)).map do |element|
      Venue.new(data['response']['groups'][0]['items'][element]["venue"])
    end
  end

  def self.venue_count(data)
    data['response']['groups'][0]['items'].length
  end

  def self.sort_by_rating(venues)
    venues.sort_by{ |venue| venue.rating }.reverse
  end

  def self.select_venues(data)
    sort_by_rating(create_venues(data)).slice(0, NUMBER_TO_SELECT)
  end

  def self.request_foursquare_data(midpoint, options, radius=DEFAULT_RADIUS)
    data = call_foursquare_api(midpoint, options, radius)
    return data, radius unless venue_count(data) < MIN_NUMBER_OF_VENUES 
    data, radius = request_foursquare_data(midpoint, options, radius + RADIUS_INCREMENT)
  end

  private

  def self.call_foursquare_api(midpoint, options, radius)
    fetch_json_from(build_foursquare_url(midpoint, options, radius))
  end

  def self.build_foursquare_url(midpoint, options, radius)
    keys = 'client_id=' + FOURSQUARE_ID + '&client_secret=' + FOURSQUARE_SECRET
    location = '&v=20130815&ll=' + midpoint.lat.to_s + ',' + midpoint.lng.to_s
    BASE_URI + keys + location + '&radius=' + radius.to_s + '&limit=' + NUMBER_OF_VENUES.to_s + '&section=' + options
  end

  def self.fetch_json_from(url)
    data = Net::HTTP.get(URI.parse(URI.encode(url)))
    JSON.parse(data)
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

	def show
		@midpoint = Midpoint.find(params[:midpoint_id])
		data, @radius = VenueDataRetriever.request_foursquare_data(@midpoint, params[:options])
		@venues = VenueDataRetriever.select_venues(data)
	end

end

app/views/venues/_sidebar.html.erb
<ul class="nav nav-tabs" role="tablist" id="categoryTab">
  <li class="active"> 
    <%= link_to midpoint_venues_path(@midpoint, options: ""), class: "find-venues" do %>
      <i class="fa fa-star"></i>
    <% end %>
  </li>
  <li>
    <%= link_to midpoint_venues_path(@midpoint, options: "food"), class: "find-venues" do %>
      <i class="fa fa-cutlery"></i>
    <% end %>
  </li>
  <li>
    <%= link_to midpoint_venues_path(@midpoint, options: "coffee"), class: "find-venues" do %>
      <i class="fa fa-coffee"></i>
    <% end %>
  </li>
  <li>
    <%= link_to midpoint_venues_path(@midpoint, options: "drinks"), class: "find-venues" do %>
      <i class="fa fa-glass"></i>
    <% end %>
  </li>
</ul>

<section id="venue-container">
</section>


<script id="venue-template" type="x-tmpl-mustache">
  <article class="venue-card">
    <div class="venue-icon"><img src="{{ bigIcon}}"></div>
    <div class="venue-name"><p>{{ name }}</p></div>
    <div class="venue-rating"><p> {{ starRating }} </p></div>
    <div class="venue-info"><em>{{ category }}{{ formattedPriceTier }}</em></div>
    <div class="venue-address"><p> {{ formattedAddress }} </p></div>
    <div class="venue-links">
    <a href="{{ detailUrl }}" class='venue-detail-url'><i class="fa fa-info-circle"> More details</i></a>
    <a href='#', class='sms-link'>
      <i class="fa fa-send"></i> SMS
    </a>
    </div>
  </article>

</script>